name: Run Vitest Tests (Unit)

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test:unit
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30
